added paths and mechanic
urlordjames/boredom pull request #1
Opened 2021-03-26 14:31 UTC by python3-Trying-py

added a water path with high base mobility but no movement mechanic. added air path with double jump mechanic. added a double jump mechanic.

2021-03-26 15:32 UTC, urlordjames requested changes
Could you also remove jump() from FirePlayer in your next commit?  It is identical to jump() in Player, I'm not sure why I override it.

2021-03-26 15:32 UTC, urlordjames commented on Scripts/AirPlayer.gd
> +func jump():
Why are we overriding this here?  This is identical to the implementation in the Player class.

2021-03-26 15:32 UTC, urlordjames commented on Scripts/AirPlayer.gd
> +func djump():
Where is this called?

2021-03-26 15:32 UTC, urlordjames commented on Scripts/Player.gd
> +func djump() -> void:
Why is this in the base class?  It is not called from the base Player.

2021-03-26 15:32 UTC, urlordjames commented on Scripts/WaterPlayer.gd
> +func jump():
Again, why are we overriding this method, it's identical to Player's implementation.  (to be fair I noticed I did this in FirePlayer too)

2021-03-26 15:32 UTC, urlordjames commented on Scripts/AirPlayer.gd
> +	default_coyote_time = INF
Maybe add a comment explaining why this makes a double jump work?

2021-03-27 03:10 UTC, urlordjames commented on Scripts/AirPlayer.gd
> +	default_coyote_time = INF
this is a bug and will break in #2

2021-03-28 02:21 UTC, python3-Trying-py commented on Scripts/AirPlayer.gd
> +func djump():
good question

2021-03-28 03:03 UTC, urlordjames requested changes
one last thing before I merge...

2021-03-28 03:03 UTC, urlordjames commented on Scripts/AirPlayer.gd
>  func djump():
this still needs to go

2021-03-28 03:05 UTC, urlordjames approved these changes

2021-03-28 03:07 UTC, merged